spring:
  data:
    mongodb:
      uri: mongodb+srv://gcp-db-user:UwL6N6IFhkVkqc52@plmgo.rrjru.mongodb.net/plm?retryWrites=true&w=majority


management:
  endpoint:
    shutdown:
      enabled: true
    info:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,metrics,info,prometheus